---
title: "Proyecto"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---

### Librerias necesarias por eso se instalan
```{r}
install.packages("lattice")
install.packages("Metrics")
install.packages("ggplot")
```

### Importar librerías para utilizar
```{r}
library(ggplot2)
library(caret)
library(Metrics)
#libreria opcional para leer el archivo
library(readr)
library(lattice)
```

### Importamos el archivo 2012 solo de departamento
## Poblacion nacional
La siguiente gráfica muestra los datos de nuestras variables. Tenemos un total de 1000 filas con 8 columnas.
```{r}
importarArchivo<-read.csv("2012/2012-departamentos.csv")
importarArchivo
```

```{r}
importarArchivoDepartamento2012<-read.csv("2012/2012-nacional.csv")
importarArchivoDepartamento2012

```

```{r}
importarArchivoDepartamento2012Municipio<-read.csv("2012/2012-departamentos-municipios.csv")
importarArchivoDepartamento2012Municipio
```


### Calculamos el coeficiente de correlación entre 3 variables.
```{r}
install.packages("corrplot")
require(corrplot)
require(lattice)
corrplot.mixed(corr = cor(importarArchivoDepartamento2012Municipio[,c("year", 
                                    "Mujer1", "Hombre1")],
                          method = "pearson"))
```
